insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (1, 'Training', 'Configurable attitude-oriented leverage', 'Bi-Weekly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (2, 'Support', 'Virtual actuating hierarchy', 'Hourly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (3, 'Sales', 'Persevering hybrid neural-net', 'Bi-Weekly', 0.02);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (4, 'Services', 'Implemented zero administration array', 'Hourly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (5, 'Research and Development', 'Diverse responsive moderator', 'Bi-Weekly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (6, 'Training', 'Versatile dynamic pricing structure', 'Bi-Weekly', 0.3);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (7, 'Services', 'Reduced real-time firmware', 'Monthly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (8, 'Training', 'Configurable client-server utilisation', 'Bi-Weekly', 0);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (9, 'Business Development', 'Compatible context-sensitive emulation', 'Monthly', 0.02);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (10, 'Research and Development', 'Centralized discrete access', 'Hourly', 0.01);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (11, 'Sales', 'Horizontal optimal info-mediaries', 'Hourly', 0.02);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (12, 'Research and Development', 'Assimilated discrete array', 'Hourly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (13, 'Accounting', 'Public-key mission-critical software', 'Bi-Weekly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (14, 'Product Management', 'Inverse upward-trending architecture', 'Hourly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (15, 'Training', 'Object-based real-time initiative', 'Monthly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (16, 'Services', 'Multi-channelled fresh-thinking portal', 'Bi-Weekly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (17, 'Legal', 'Re-engineered static instruction set', 'Monthly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (18, 'Accounting', 'Vision-oriented grid-enabled definition', 'Monthly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (19, 'Engineering', 'Multi-layered web-enabled migration', 'Monthly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (20, 'Training', 'Monitored responsive protocol', 'Monthly', 0.02);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (21, 'Legal', 'Progressive national encryption', 'Monthly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (22, 'Legal', 'Compatible explicit middleware', 'Monthly', 0.3);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (23, 'Legal', 'Intuitive national synergy', 'Monthly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (24, 'Engineering', 'Synergistic attitude-oriented flexibility', 'Monthly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (25, 'Training', 'Universal fresh-thinking neural-net', 'Bi-Weekly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (26, 'Engineering', 'Mandatory fresh-thinking product', 'Bi-Weekly', 0.3);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (27, 'Product Management', 'Versatile human-resource concept', 'Bi-Weekly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (28, 'Research and Development', 'Right-sized composite concept', 'Hourly', 0.3);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (29, 'Marketing', 'Reactive dedicated orchestration', 'Monthly', 0.01);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (30, 'Business Development', 'Fully-configurable demand-driven forecast', 'Monthly', 0);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (31, 'Accounting', 'Configurable zero defect benchmark', 'Bi-Weekly', 0);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (32, 'Marketing', 'Balanced dynamic website', 'Hourly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (33, 'Services', 'Diverse local installation', 'Monthly', 0.3);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (34, 'Support', 'Polarised 24/7 encoding', 'Hourly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (35, 'Marketing', 'Re-contextualized national hardware', 'Monthly', 0);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (36, 'Support', 'Right-sized national intranet', 'Bi-Weekly', 0.01);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (37, 'Accounting', 'Automated mission-critical system engine', 'Hourly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (38, 'Product Management', 'Public-key multimedia task-force', 'Hourly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (39, 'Accounting', 'Proactive multi-state installation', 'Hourly', 0);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (40, 'Support', 'Total didactic framework', 'Monthly', 0.02);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (41, 'Business Development', 'Re-engineered heuristic service-desk', 'Hourly', 0.01);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (42, 'Sales', 'Profit-focused system-worthy conglomeration', 'Bi-Weekly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (43, 'Sales', 'Object-based systematic adapter', 'Bi-Weekly', 0.03);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (44, 'Legal', 'Phased user-facing internet solution', 'Hourly', 0.3);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (45, 'Legal', 'Monitored reciprocal analyzer', 'Bi-Weekly', 0.02);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (46, 'Accounting', 'Operative reciprocal matrices', 'Bi-Weekly', 0.01);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (47, 'Accounting', 'Exclusive foreground approach', 'Hourly', 0.05);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (48, 'Legal', 'Re-engineered well-modulated encryption', 'Hourly', 0.3);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (49, 'Business Development', 'Synchronised 5th generation process improvement', 'Hourly', 0.02);
insert into Employee_Type ( employee_type_id, employee_type,   employee_type_desc, pay_type, compensation_package) values (50, 'Human Resources', 'Operative reciprocal alliance', 'Hourly', 0.02);
