insert into employee_role (employee_role_id, role_name, role_desc) values (1, 'Product Manager', 'Decentralized systemic productivity');
insert into employee_role (employee_role_id, role_name, role_desc) values (2, 'Receptionist', 'Total fresh-thinking policy');
insert into employee_role (employee_role_id, role_name, role_desc) values (3, 'Product Manager', 'Visionary zero defect migration');
insert into employee_role (employee_role_id, role_name, role_desc) values (4, 'Product Manager', 'Robust hybrid frame');
insert into employee_role (employee_role_id, role_name, role_desc) values (5, 'Receptionist', 'User-centric multi-state productivity');
insert into employee_role (employee_role_id, role_name, role_desc) values (6, 'Engineer', 'Managed systematic intranet');
insert into employee_role (employee_role_id, role_name, role_desc) values (7, 'Marketing Head', 'Fundamental system-worthy neural-net');
insert into employee_role (employee_role_id, role_name, role_desc) values (8, 'DBA specialist', 'Intuitive global help-desk');
insert into employee_role (employee_role_id, role_name, role_desc) values (9, 'Sales', 'Organic object-oriented superstructure');
insert into employee_role (employee_role_id, role_name, role_desc) values (10, 'Marketing Head', 'Programmable encompassing capacity');
insert into employee_role (employee_role_id, role_name, role_desc) values (11, 'QA Tester', 'Universal transitional frame');
insert into employee_role (employee_role_id, role_name, role_desc) values (12, 'CTO', 'Object-based executive algorithm');
insert into employee_role (employee_role_id, role_name, role_desc) values (13, 'Marketing Head', 'Focused client-driven contingency');
insert into employee_role (employee_role_id, role_name, role_desc) values (14, 'QA Tester', 'Devolved holistic leverage');
insert into employee_role (employee_role_id, role_name, role_desc) values (15, 'DevOps', 'Multi-tiered non-volatile policy');
insert into employee_role (employee_role_id, role_name, role_desc) values (16, 'DBA specialist', 'Programmable disintermediate moratorium');
insert into employee_role (employee_role_id, role_name, role_desc) values (17, 'CEO', 'Synchronised 24/7 functionalities');
insert into employee_role (employee_role_id, role_name, role_desc) values (18, 'Receptionist', 'Inverse even-keeled policy');
insert into employee_role (employee_role_id, role_name, role_desc) values (19, 'QA Tester', 'Universal even-keeled conglomeration');
insert into employee_role (employee_role_id, role_name, role_desc) values (20, 'Manager', 'Streamlined human-resource benchmark');
insert into employee_role (employee_role_id, role_name, role_desc) values (21, 'HR', 'Down-sized bottom-line synergy');
insert into employee_role (employee_role_id, role_name, role_desc) values (22, 'DevOps', 'Organic client-driven contingency');
insert into employee_role (employee_role_id, role_name, role_desc) values (23, 'CTO', 'Distributed high-level application');
insert into employee_role (employee_role_id, role_name, role_desc) values (24, 'Marketing Head', 'Balanced incremental Graphical User Interface');
insert into employee_role (employee_role_id, role_name, role_desc) values (25, 'Manager', 'Assimilated heuristic local area network');
insert into employee_role (employee_role_id, role_name, role_desc) values (26, 'QA Tester', 'Total even-keeled concept');
insert into employee_role (employee_role_id, role_name, role_desc) values (27, 'HR', 'Persevering human-resource portal');
insert into employee_role (employee_role_id, role_name, role_desc) values (28, 'Sales', 'Fully-configurable scalable success');
insert into employee_role (employee_role_id, role_name, role_desc) values (29, 'DBA specialist', 'Seamless tertiary synergy');
insert into employee_role (employee_role_id, role_name, role_desc) values (30, 'CEO', 'Multi-tiered web-enabled synergy');
insert into employee_role (employee_role_id, role_name, role_desc) values (31, 'Engineer', 'Function-based didactic throughput');
insert into employee_role (employee_role_id, role_name, role_desc) values (32, 'HR', 'Multi-lateral regional benchmark');
insert into employee_role (employee_role_id, role_name, role_desc) values (33, 'DevOps', 'Grass-roots background Graphic Interface');
insert into employee_role (employee_role_id, role_name, role_desc) values (34, 'HR', 'Front-line motivating functionalities');
insert into employee_role (employee_role_id, role_name, role_desc) values (35, 'QA Tester', 'Integrated actuating frame');
insert into employee_role (employee_role_id, role_name, role_desc) values (36, 'Engineer', 'Function-based full-range matrices');
insert into employee_role (employee_role_id, role_name, role_desc) values (37, 'Engineer', 'Right-sized optimal system engine');
insert into employee_role (employee_role_id, role_name, role_desc) values (38, 'QA lead', 'Organic web-enabled interface');
insert into employee_role (employee_role_id, role_name, role_desc) values (39, 'Engineer', 'Devolved zero administration standardization');
insert into employee_role (employee_role_id, role_name, role_desc) values (40, 'Manager', 'Multi-layered real-time database');
insert into employee_role (employee_role_id, role_name, role_desc) values (41, 'Product Manager', 'Operative systemic application');
insert into employee_role (employee_role_id, role_name, role_desc) values (42, 'Receptionist', 'Universal non-volatile moratorium');
insert into employee_role (employee_role_id, role_name, role_desc) values (43, 'QA lead', 'Mandatory incremental leverage');
insert into employee_role (employee_role_id, role_name, role_desc) values (44, 'CTO', 'Universal real-time knowledge user');
insert into employee_role (employee_role_id, role_name, role_desc) values (45, 'DBA specialist', 'Fully-configurable incremental database');
insert into employee_role (employee_role_id, role_name, role_desc) values (46, 'DBA specialist', 'Implemented transitional strategy');
insert into employee_role (employee_role_id, role_name, role_desc) values (47, 'QA Tester', 'Team-oriented mobile productivity');
insert into employee_role (employee_role_id, role_name, role_desc) values (48, 'CTO', 'Business-focused optimizing core');
insert into employee_role (employee_role_id, role_name, role_desc) values (49, 'QA lead', 'Ergonomic exuding matrices');
insert into employee_role (employee_role_id, role_name, role_desc) values (50, 'Sales', 'Customizable motivating analyzer');
